'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { ContentPublishStatus, GameArticleCategory } from '@zenx-go/api-client';
import { api } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';

export default function GameArticlesPage() {
  const { subdomain } = useParams<{ subdomain: string }>(); const client = useQueryClient();
  const [search, setSearch] = useState(''); const [debounced, setDebounced] = useState(''); const [category, setCategory] = useState<'' | GameArticleCategory>(''); const [status, setStatus] = useState<'' | ContentPublishStatus>(''); const [trash, setTrash] = useState(false); const [page, setPage] = useState(1);
  const context = useQuery({ queryKey: ['game-admin', 'context', subdomain], queryFn: () => api.gameAdmin.context(subdomain), retry: false });
  useEffect(() => { const timer = window.setTimeout(() => { setDebounced(search.trim()); setPage(1); }, 300); return () => window.clearTimeout(timer); }, [search]);
  const articles = useQuery({ queryKey: ['game-admin', 'articles', context.data?.game.id, page, debounced, category, status, trash], queryFn: () => api.gameAdmin.content.articles(context.data!.game.id, { page, pageSize: 15, search: debounced || undefined, category: category || undefined, status: status || undefined, deletedOnly: trash || undefined }), enabled: Boolean(context.data), retry: false, placeholderData: (previous) => previous });
  const remove = useMutation({ mutationFn: (id: string) => api.gameAdmin.content.deleteArticle(context.data!.game.id, id), onSuccess: () => void client.invalidateQueries({ queryKey: ['game-admin', 'articles', context.data?.game.id] }) });
  const restore = useMutation({ mutationFn: (id: string) => api.gameAdmin.content.restoreArticle(context.data!.game.id, id), onSuccess: () => void client.invalidateQueries({ queryKey: ['game-admin', 'articles', context.data?.game.id] }) });
  const base = `/game-admin/${encodeURIComponent(subdomain)}/articles`;
  if (context.isError || articles.isError) return <p className="text-sm text-red-600">Bạn không có quyền xem nội dung game này hoặc tài nguyên không thuộc game hiện tại.</p>;
  return <div className="space-y-4"><header className="flex items-center justify-between"><div><h1 className="text-3xl font-black">Bài viết</h1><p className="mt-1 text-sm text-slate-500">Nội dung chỉ thuộc {context.data?.game.name ?? 'game hiện tại'}.</p></div><Button asChild><Link href={`${base}/new`}>Viết bài mới</Link></Button></header><div className="flex flex-wrap gap-2"><Button variant={!trash ? 'default' : 'outline'} size="sm" onClick={() => { setTrash(false); setPage(1); }}>Tất cả</Button><Button variant={status === 'PUBLISHED' ? 'default' : 'outline'} size="sm" onClick={() => { setTrash(false); setStatus(status === 'PUBLISHED' ? '' : 'PUBLISHED'); setPage(1); }}>Đã xuất bản</Button><Button variant={status === 'DRAFT' ? 'default' : 'outline'} size="sm" onClick={() => { setTrash(false); setStatus(status === 'DRAFT' ? '' : 'DRAFT'); setPage(1); }}>Bản nháp</Button><Button variant={trash ? 'default' : 'outline'} size="sm" onClick={() => { setTrash(true); setStatus(''); setPage(1); }}>Thùng rác</Button></div><div className="grid gap-2 md:grid-cols-3"><Input aria-label="Tìm bài viết" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tìm bài viết" /><Select aria-label="Lọc chuyên mục" value={category} onChange={(e) => { setCategory(e.target.value as '' | GameArticleCategory); setPage(1); }}><option value="">Tất cả chuyên mục</option><option value="ANNOUNCEMENT">Thông báo</option><option value="DEVELOPMENT_UPDATE">Cập nhật phát triển</option><option value="EVENT">Sự kiện</option><option value="MAINTENANCE">Bảo trì</option></Select><Select aria-label="Lọc trạng thái" value={status} onChange={(e) => { setStatus(e.target.value as '' | ContentPublishStatus); setPage(1); }}><option value="">Tất cả trạng thái</option><option value="DRAFT">Bản nháp</option><option value="PUBLISHED">Đã xuất bản</option></Select></div><div className="divide-y rounded-xl border bg-white">{articles.data?.items.map((article) => <div key={article.id} className="flex items-center justify-between gap-3 p-4"><div><Link className="font-semibold hover:underline" href={`${base}/${article.id}`}>{article.title}</Link><p className="text-sm text-slate-500">{article.status} · {article.category}</p></div>{trash ? <Button size="sm" variant="outline" onClick={() => restore.mutate(article.id)}>Khôi phục</Button> : <Button size="sm" variant="outline" onClick={() => { if (window.confirm(`Chuyển “${article.title}” vào thùng rác?`)) remove.mutate(article.id); }}>Xóa</Button>}</div>)}{articles.data?.items.length === 0 ? <p className="p-6 text-sm text-slate-500">Chưa có bài viết.</p> : null}</div><Pagination page={page} total={articles.data?.totalPages ?? 1} onChange={setPage} /></div>;
}
function Pagination({ page, total, onChange }: { page: number; total: number; onChange: (page: number) => void }) { return <div className="flex justify-end gap-2"><Button size="sm" variant="outline" disabled={page <= 1} onClick={() => onChange(page - 1)}>Trước</Button><span className="px-2 py-1 text-sm">{page}/{Math.max(1, total)}</span><Button size="sm" variant="outline" disabled={page >= total} onClick={() => onChange(page + 1)}>Sau</Button></div>; }
