'use client';

import Link from 'next/link';
import { ArrowRight, Download, Globe2, Sparkles } from 'lucide-react';
import { useGame } from '@/components/game/game-context';
import { gameUrl, portalUrl } from '@/lib/domain';
import { ThiTranMayHome } from '@/components/game/thi-tran-may-home';
import { LucDiaDamMeHome } from '@/components/game/luc-dia-dam-me-home';

export default function GameHomePage() {
  const game = useGame();

  if (game.slug === 'thi-tran-may' || game.subdomain === 'thitranmay') {
    return <ThiTranMayHome />;
  }

  if (game.slug === 'luc-dia-dam-me' || game.subdomain === 'lucdia') {
    return <LucDiaDamMeHome />;
  }

  const sections = game.featureConfig.sections;
  const primaryAction = game.lifecycleStatus === 'LIVE' || game.lifecycleStatus === 'OPEN_BETA' ? 'Chơi ngay' : game.lifecycleStatus === 'CLOSED_BETA' || game.lifecycleStatus === 'INTERNAL_TEST' ? 'Đăng ký test' : 'Theo dõi dự án';
  const primaryActionHref = game.recordType === 'DEMO' ? portalUrl('/games') : gameUrl(game.subdomain, '/gioi-thieu');
  return <div>
    {sections.includes('HERO') ? <section className="relative isolate overflow-hidden bg-slate-950 text-white"><picture><source media="(max-width: 767px)" srcSet={game.heroMobileUrl ?? game.heroDesktopUrl ?? game.coverUrl ?? undefined} /><img src={game.heroDesktopUrl ?? game.coverUrl ?? undefined} alt="" className="absolute inset-0 -z-20 size-full object-cover opacity-70" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black/85 via-black/60 to-black/20" /></picture><div className="mx-auto flex min-h-[560px] max-w-7xl items-end px-4 pb-16 pt-28 sm:px-6 lg:px-8"><div className="max-w-2xl"><div className="mb-5 flex flex-wrap items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-[var(--game-secondary)]"><span className="rounded-full border border-current px-3 py-1">{game.recordType === 'DEMO' ? 'Concept / Demo' : game.themePreset}</span><span>{game.lifecycleStatus.replaceAll('_', ' ')}</span></div><h1 className="text-4xl font-black tracking-tight sm:text-6xl">{game.name}</h1><p className="mt-5 max-w-xl text-lg leading-relaxed text-white/80">{game.tagline}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={primaryActionHref} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[var(--game-primary)] px-6 text-sm font-bold text-white">{primaryAction} <ArrowRight className="size-4" /></Link>{sections.includes('ROADMAP_PREVIEW') ? <Link href={gameUrl(game.subdomain, '/roadmap')} className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/30 px-6 text-sm font-bold text-white hover:bg-white/10">Xem lộ trình</Link> : null}</div></div></div></section> : null}
    <div className="mx-auto max-w-7xl space-y-20 px-4 py-16 sm:px-6 lg:px-8">
      {sections.includes('GAME_INTRODUCTION') ? <section className="grid gap-8 md:grid-cols-[1.2fr_0.8fr] md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--game-primary)]">Về dự án</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Một thế giới đang được xây dựng</h2><p className="mt-5 max-w-2xl text-base leading-8 opacity-75">{game.longDescription ?? game.shortDescription}</p></div><div className="rounded-3xl border border-black/10 bg-white/60 p-6 shadow-sm"><div className="flex items-center gap-3"><Globe2 className="size-6 text-[var(--game-primary)]" /><span className="font-bold">Nền tảng</span></div><div className="mt-5 flex flex-wrap gap-2">{game.platforms.map((platform) => <span key={platform} className="rounded-full border border-black/10 px-3 py-1.5 text-sm font-semibold">{platform}</span>)}</div><p className="mt-5 text-sm opacity-65">{game.shortDescription}</p></div></section> : null}
      {sections.includes('FEATURE_GRID') ? <section><SectionHeading eyebrow="Điểm nổi bật" title="Được tạo nên cho hành trình của bạn" /><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{['Thế giới có chiều sâu', 'Trải nghiệm đa nền tảng', 'Cộng đồng đồng hành', 'Lộ trình minh bạch'].map((item, index) => <div key={item} className="rounded-2xl border border-black/10 bg-white/55 p-6"><Sparkles className="size-5 text-[var(--game-primary)]" /><h3 className="mt-5 font-bold">{item}</h3><p className="mt-2 text-sm leading-6 opacity-70">Khám phá những hệ thống được thiết kế xoay quanh thế giới {game.name}.</p><span className="mt-5 block text-xs font-bold opacity-50">0{index + 1}</span></div>)}</div></section> : null}
      {sections.includes('PLATFORM_CARDS') ? <section><SectionHeading eyebrow="Sẵn sàng trải nghiệm" title="Nền tảng hỗ trợ" /><div className="mt-8 grid gap-4 sm:grid-cols-3">{game.platforms.map((platform) => <Link key={platform} href={gameUrl(game.subdomain, '/tai-game')} className="group rounded-2xl border border-black/10 bg-white/55 p-6 hover:border-[var(--game-primary)]"><Download className="size-5 text-[var(--game-primary)]" /><h3 className="mt-5 font-bold">{platform}</h3><p className="mt-2 text-sm opacity-65">{game.featureConfig.downloads === 'COMING_SOON' ? 'Sắp ra mắt' : 'Xem thông tin'}</p><ArrowRight className="mt-5 size-4 opacity-50 transition-transform group-hover:translate-x-1" /></Link>)}</div></section> : null}
      {sections.includes('ROADMAP_PREVIEW') && game.milestones.length ? <section><SectionHeading eyebrow="Lộ trình phát triển" title="Từng bước xây dựng thế giới" /><div className="mt-8 grid gap-3 md:grid-cols-3">{game.milestones.slice(0, 3).map((milestone) => <div key={milestone.title} className="rounded-2xl border border-black/10 bg-white/55 p-5"><div className="flex items-center justify-between gap-3 text-xs font-bold opacity-60"><span>{milestone.displayPeriod}</span><span>{milestone.status.replaceAll('_', ' ')}</span></div><h3 className="mt-4 font-bold">{milestone.title}</h3><p className="mt-2 text-sm leading-6 opacity-70">{milestone.description}</p></div>)}</div><Link href={gameUrl(game.subdomain, '/roadmap')} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[var(--game-primary)]">Xem toàn bộ lộ trình <ArrowRight className="size-4" /></Link></section> : null}
      {sections.includes('ARTICLE_GRID') && game.articles.length ? <section><SectionHeading eyebrow="Nhật ký phát triển" title="Nhật ký phát triển" /><div className="mt-8 grid gap-5 md:grid-cols-3">{game.articles.slice(0, 3).map((article) => <Link key={article.slug} href={gameUrl(game.subdomain, `/tin-tuc/${article.slug}`)} className="overflow-hidden rounded-2xl border border-black/10 bg-white/55 hover:border-[var(--game-primary)]">{article.coverImageUrl ? <img src={article.coverImageUrl} alt="" className="aspect-[16/9] w-full object-cover" /> : null}<div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-[var(--game-primary)]">{article.category.replaceAll('_', ' ')}</p><h3 className="mt-3 font-bold">{article.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 opacity-70">{article.excerpt}</p></div></Link>)}</div></section> : null}
      {sections.includes('DEVELOPMENT_PROGRESS') ? <section className="rounded-3xl bg-black/[0.04] p-7 sm:p-10"><div className="flex flex-col gap-8 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--game-primary)]">Tiến độ dự án</p><h2 className="mt-3 text-3xl font-black">Đang được xây dựng cùng cộng đồng</h2></div><div className="w-full max-w-sm"><div className="flex justify-between text-sm font-bold"><span>Tiến độ hiện tại</span><span>60%</span></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-black/10"><div className="h-full w-[60%] rounded-full bg-[var(--game-primary)]" /></div></div></div></section> : null}
      {sections.includes('COMMUNITY_CTA') ? <section className="rounded-3xl bg-[var(--game-primary)] p-8 text-white sm:p-12"><div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-white/70">Cùng xây dựng thế giới</p><h2 className="mt-3 text-3xl font-black">Theo dõi những cập nhật mới nhất</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/80">Đăng ký tài khoản ZENX GO để không bỏ lỡ thông tin về {game.name}.</p></div><Link href={game.recordType === 'DEMO' ? portalUrl('/games') : gameUrl(game.subdomain, '/tin-tuc')} className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-white px-6 text-sm font-bold text-[var(--game-primary)]">{game.recordType === 'DEMO' ? 'Khám phá Game Hub' : 'Xem cập nhật'} <ArrowRight className="size-4" /></Link></div></section> : null}
    </div>
  </div>;
}

function SectionHeading({ eyebrow, title }: { eyebrow: string; title: string }) { return <div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--game-primary)]">{eyebrow}</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">{title}</h2></div>; }
