export default () => ({
  nodeEnv: process.env.NODE_ENV ?? 'development',
  port: Number(process.env.API_PORT ?? 4000),
  webOrigin: process.env.WEB_ORIGIN ?? 'http://localhost:3000',
  databaseUrl: process.env.DATABASE_URL,
  jwtAccessSecret: process.env.JWT_ACCESS_SECRET ?? 'development-access-secret-change-me-32',
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET ?? 'development-refresh-secret-change-me-32',
  cookieSecure: process.env.COOKIE_SECURE === 'true',
  cookieDomain: process.env.COOKIE_DOMAIN || undefined,
  termsVersion: process.env.TERMS_VERSION ?? '2026-01',
  privacyVersion: process.env.PRIVACY_VERSION ?? '2026-01',
  otpSmsProvider: process.env.OTP_SMS_PROVIDER ?? 'mock',
  otpZaloProvider: process.env.OTP_ZALO_PROVIDER ?? 'mock',
  otpEmailProvider: process.env.OTP_EMAIL_PROVIDER ?? 'mock',
  demoMode: process.env.DEMO_MODE === 'true',
  otpMockFixedCode: process.env.OTP_MOCK_FIXED_CODE,
  paymentProvider: process.env.PAYMENT_PROVIDER ?? 'mock',
  sepay: {
    bankAccount: process.env.SEPAY_BANK_ACCOUNT,
    bankCode: process.env.SEPAY_BANK_CODE,
    accountHolder: process.env.SEPAY_ACCOUNT_HOLDER,
    webhookSecret: process.env.SEPAY_WEBHOOK_SECRET,
    transferPrefix: process.env.SEPAY_TRANSFER_PREFIX ?? 'ZENX',
    qrBaseUrl: process.env.SEPAY_QR_BASE_URL ?? 'https://vietqr.app/img',
  },
  uploadDir: process.env.UPLOAD_DIR ?? 'uploads',
  rateLimitTtlMs: Number(process.env.RATE_LIMIT_TTL_MS ?? 60_000),
  rateLimitMax: Number(process.env.RATE_LIMIT_MAX ?? 30),
  oauthStateSecret: process.env.OAUTH_STATE_SECRET || process.env.JWT_REFRESH_SECRET || 'development-refresh-secret-change-me-32',
  oauth: {
    google: {
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      redirectUri: process.env.GOOGLE_REDIRECT_URI,
      authorizationUrl: process.env.GOOGLE_AUTHORIZATION_URL,
      tokenUrl: process.env.GOOGLE_TOKEN_URL,
      userInfoUrl: process.env.GOOGLE_USERINFO_URL,
    },
    facebook: {
      clientId: process.env.FACEBOOK_CLIENT_ID,
      clientSecret: process.env.FACEBOOK_CLIENT_SECRET,
      redirectUri: process.env.FACEBOOK_REDIRECT_URI,
      authorizationUrl: process.env.FACEBOOK_AUTHORIZATION_URL,
      tokenUrl: process.env.FACEBOOK_TOKEN_URL,
      userInfoUrl: process.env.FACEBOOK_USERINFO_URL,
    },
  },
});
