export const ErrorCode = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ALREADY_USED: 'OTP_ALREADY_USED',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  VERIFICATION_TOKEN_INVALID: 'VERIFICATION_TOKEN_INVALID',
  SOCIAL_ALREADY_LINKED: 'SOCIAL_ALREADY_LINKED',
  SOCIAL_LINKED_TO_ANOTHER_ACCOUNT: 'SOCIAL_LINKED_TO_ANOTHER_ACCOUNT',
  CANNOT_UNLINK_LAST_LOGIN_METHOD: 'CANNOT_UNLINK_LAST_LOGIN_METHOD',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  DUPLICATE_WALLET_TRANSACTION: 'DUPLICATE_WALLET_TRANSACTION',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
  INVALID_PAYMENT_CALLBACK: 'INVALID_PAYMENT_CALLBACK',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

export class DomainError extends Error {
  constructor(
    public readonly code: ErrorCodeValue,
    message: string = code,
    public readonly status = 400,
  ) {
    super(message);
    this.name = 'DomainError';
  }
}

export type ApiError = { code: string; message: string; details?: unknown };
export type ApiResponse<T> = { data: T | null; error: ApiError | null };
