export const ErrorCode = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  REFRESH_IN_PROGRESS: 'REFRESH_IN_PROGRESS',
  PASSWORD_REUSE: 'PASSWORD_REUSE',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ALREADY_USED: 'OTP_ALREADY_USED',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  VERIFICATION_TOKEN_INVALID: 'VERIFICATION_TOKEN_INVALID',
  SOCIAL_ALREADY_LINKED: 'SOCIAL_ALREADY_LINKED',
  SOCIAL_LINKED_TO_ANOTHER_ACCOUNT: 'SOCIAL_LINKED_TO_ANOTHER_ACCOUNT',
  SOCIAL_NOT_CONFIGURED: 'SOCIAL_NOT_CONFIGURED',
  SOCIAL_NOT_LINKED: 'SOCIAL_NOT_LINKED',
  SOCIAL_OAUTH_REQUIRED: 'SOCIAL_OAUTH_REQUIRED',
  SOCIAL_OAUTH_FAILED: 'SOCIAL_OAUTH_FAILED',
  INVALID_OAUTH_STATE: 'INVALID_OAUTH_STATE',
  INVALID_SOCIAL_PROVIDER: 'INVALID_SOCIAL_PROVIDER',
  CANNOT_UNLINK_LAST_LOGIN_METHOD: 'CANNOT_UNLINK_LAST_LOGIN_METHOD',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  DUPLICATE_WALLET_TRANSACTION: 'DUPLICATE_WALLET_TRANSACTION',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
  INVALID_PAYMENT_CALLBACK: 'INVALID_PAYMENT_CALLBACK',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',
  INVALID_TRANSACTION_FILTER: 'INVALID_TRANSACTION_FILTER',
  EXPORT_LIMIT_EXCEEDED: 'EXPORT_LIMIT_EXCEEDED',
  INVALID_AVATAR: 'INVALID_AVATAR',
  SUPPORT_CATEGORY_NOT_FOUND: 'SUPPORT_CATEGORY_NOT_FOUND',
  SUPPORT_TICKET_NOT_FOUND: 'SUPPORT_TICKET_NOT_FOUND',
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  GAME_ARTICLE_NOT_FOUND: 'GAME_ARTICLE_NOT_FOUND',
  GAME_CONFIG_INVALID: 'GAME_CONFIG_INVALID',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

export class DomainError extends Error {
  constructor(
    public readonly code: ErrorCodeValue,
    message: string = code,
    public readonly status = 400,
  ) {
    super(message);
    this.name = 'DomainError';
  }
}

export type ApiError = { code: string; message: string; details?: unknown };
export type ApiResponse<T> = { data: T | null; error: ApiError | null };
