'use client';

import { useParams } from 'next/navigation';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Textarea } from '@/components/ui/textarea';

export default function GameEventsPage() {
  const { subdomain } = useParams<{ subdomain: string }>(); const client = useQueryClient(); const [open, setOpen] = useState(false); const [title, setTitle] = useState(''); const [slug, setSlug] = useState(''); const [excerpt, setExcerpt] = useState(''); const [content, setContent] = useState(''); const [startsAt, setStartsAt] = useState('');
  const context = useQuery({ queryKey: ['game-admin', 'context', subdomain], queryFn: () => api.gameAdmin.context(subdomain), retry: false }); const events = useQuery({ queryKey: ['game-admin', 'events', context.data?.game.id], queryFn: () => api.gameAdmin.content.events(context.data!.game.id), enabled: Boolean(context.data), retry: false });
  const create = useMutation({ mutationFn: () => api.gameAdmin.content.createEvent(context.data!.game.id, { title, slug, excerpt, content, startsAt: new Date(startsAt).toISOString(), status: 'PUBLISHED' }), onSuccess: () => { setOpen(false); void client.invalidateQueries({ queryKey: ['game-admin', 'events'] }); } });
  return <><div className="mb-7 flex items-center justify-between"><div><h1 className="text-3xl font-black">Sự kiện</h1><p className="mt-1 text-sm text-slate-500">Sự kiện được xuất bản trong đúng game hiện tại.</p></div><Button onClick={() => setOpen(true)}>Tạo sự kiện</Button></div>{open ? <div className="mb-6 rounded-xl border bg-white p-5"><div className="grid gap-3 md:grid-cols-2"><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Tiêu đề" /><Input value={slug} onChange={(e) => setSlug(e.target.value)} placeholder="slug" /></div><Input className="mt-3" value={excerpt} onChange={(e) => setExcerpt(e.target.value)} placeholder="Tóm tắt" /><Input className="mt-3" type="datetime-local" value={startsAt} onChange={(e) => setStartsAt(e.target.value)} /><Textarea className="mt-3 min-h-40" value={content} onChange={(e) => setContent(e.target.value)} placeholder="Nội dung Markdown" /><div className="mt-4 flex gap-3"><Button disabled={!title || !slug || !excerpt || !content || !startsAt || create.isPending} onClick={() => create.mutate()}>Xuất bản</Button><Button variant="outline" onClick={() => setOpen(false)}>Hủy</Button></div></div> : null}<div className="divide-y overflow-hidden rounded-xl border bg-white">{events.data?.items.map((event) => <div key={event.id} className="p-4"><p className="font-semibold">{event.title}</p><p className="mt-1 text-sm text-slate-500">{event.status} · {new Date(event.startsAt).toLocaleString('vi-VN')}</p></div>)}{events.data?.items.length === 0 ? <p className="p-6 text-sm text-slate-500">Chưa có sự kiện.</p> : null}</div></>;
}
