'use client';

import { useParams } from 'next/navigation'; import { useEffect, useState } from 'react'; import { useMutation, useQuery } from '@tanstack/react-query'; import { api } from '@/lib/api'; import { Button } from '@/components/ui/button'; import { Textarea } from '@/components/ui/textarea';

export default function GamePresentationPage() {
  const { subdomain } = useParams<{ subdomain: string }>(); const context = useQuery({ queryKey: ['game-admin', 'context', subdomain], queryFn: () => api.gameAdmin.context(subdomain), retry: false }); const presentation = useQuery({ queryKey: ['game-admin', 'presentation', context.data?.game.id], queryFn: () => api.gameAdmin.content.presentation(context.data!.game.id), enabled: Boolean(context.data), retry: false }); const [theme, setTheme] = useState(''); const [features, setFeatures] = useState(''); const [page, setPage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (presentation.data) { setTheme(presentation.data.themeConfig); setFeatures(presentation.data.featureConfig); setPage(presentation.data.pageConfig); } }, [presentation.data]);
  const save = useMutation({ mutationFn: () => { try { return api.gameAdmin.content.updatePresentation(context.data!.game.id, { expectedUpdatedAt: presentation.data!.updatedAt, themeConfig: JSON.parse(theme), featureConfig: JSON.parse(features), pageConfig: JSON.parse(page) }); } catch { return Promise.reject(new Error('JSON không hợp lệ')); } }, onError: (value) => setError(value.message) });
  if (!presentation.data) return <p className="text-sm text-slate-500">Đang tải giao diện…</p>; return <><div className="mb-7"><h1 className="text-3xl font-black">Giao diện game</h1><p className="mt-1 text-sm text-slate-500">Cấu hình template theo game; thay đổi được lưu audit.</p></div><div className="space-y-4"><label className="block text-sm font-semibold">Theme JSON<Textarea className="mt-2 min-h-40 font-mono text-xs" value={theme} onChange={(e) => setTheme(e.target.value)} /></label><label className="block text-sm font-semibold">Feature JSON<Textarea className="mt-2 min-h-40 font-mono text-xs" value={features} onChange={(e) => setFeatures(e.target.value)} /></label><label className="block text-sm font-semibold">Page JSON<Textarea className="mt-2 min-h-56 font-mono text-xs" value={page} onChange={(e) => setPage(e.target.value)} /></label>{error ? <p className="text-sm text-red-600">{error}</p> : null}<Button disabled={save.isPending} onClick={() => save.mutate()}>Lưu giao diện</Button></div></>;
}
